import type { Metadata } from "next";import "./globals.css";
import { Manrope, Plus_Jakarta_Sans } from "next/font/google";

// Manrope font
const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap",
  weight:  ["200" , "300" ,"400", "500", "600", "700","800"], // jitne weights chahiye utne hi load karo
});

// Plus Jakarta Sans font
const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta",
  display: "swap",
  weight:  ["200" , "300" ,"400", "500", "600", "700","800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${plusJakarta.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
